"""Initial database schema

Revision ID: 2382f8496c1c
Revises: 
Create Date: 2025-09-16 14:48:47.295099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2382f8496c1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategy_signals', 'ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_strategy_signals_strategy'), 'strategy_signals', ['strategy'], unique=False)
    op.create_index(op.f('ix_strategy_signals_symbol'), 'strategy_signals', ['symbol'], unique=False)
    op.create_index(op.f('ix_strategy_signals_ts'), 'strategy_signals', ['ts'], unique=False)
    op.drop_column('strategy_signals', 'signal_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_signals', sa.Column('signal_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_strategy_signals_ts'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_symbol'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_strategy'), table_name='strategy_signals')
    op.alter_column('strategy_signals', 'ts',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
